[package]
name = "pythia"
version = "0.0.1"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "main" }

[addresses]
std = "0x1"
initia_std = "0x1"
pythia = "_"

[dev-addresses]
pythia = "0x42"
